# default text color
set color_win_fg=246

# overall background color
set color_win_bg=default

# command-line colors
set color_cmdline_bg=default
set color_cmdline_fg=default
set color_error=124
set color_info=172
set color_separator=236

# bottom status line
set color_statusline_bg=235
set color_statusline_fg=245

# bottom title line
set color_titleline_bg=236
set color_titleline_fg=229

# top title area
set color_win_title_bg=236
set color_win_title_fg=252

# unselected currently playing track's text
set color_win_cur=184
set color_win_cur=184
set color_win_cur_attr=bold

# active selection for currently playing track
set color_win_cur_sel_bg=58
set color_win_cur_sel_fg=226
set color_win_cur_sel_attr=bold

# inactive selection for currently playing track
set color_win_inactive_cur_sel_bg=236
set color_win_inactive_cur_sel_fg=184

# active selection
set color_win_sel_bg=58
set color_win_sel_fg=229

# inactive selection
set color_win_inactive_sel_bg=235
set color_win_inactive_sel_fg=253

# directory listing color
set color_win_dir=229
