#!/bin/sh
#
# Copyright 2005 Timo Hirvonen
#
# This file is licensed under the GPLv2.

if test $# -lt 2
then
	echo "expecting at least 2 arguments"
	exit 1
fi
to="${DESTDIR}${1}"
shift
install -d -m755 "${to}"
for i in "$@"
do
	echo "INSTALL ${to}/${i}"
	install "$i" "${to}"
done
