name: Build
on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        cc: [gcc, clang]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          ./configure CC="${{matrix.cc}}"
          make
